services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=hw8
    ports:
      - "5432:5432"
    restart: unless-stopped
